default: &default

  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: idea_box_development

test:
  <<: *default
  database: idea_box_test

production:
  <<: *default
  database: idea_box_production
  password: <%= ENV['IDEA_BOX_DATABASE_PASSWORD'] %>
